# {{=<% %>=}}
---
apiVersion: deployment.krateo.io/v1alpha1
kind: AwsStack
metadata:
  name: <%#norm%>{{name}}<%/norm%>-aws-stack
spec:
  owner: mauro
  title: <% name %>
  description: <% description %>
  icon: "fa-brands fa-aws"
  tags:
    - aws
    - stack
    - infrastructure
    - rds
  links:
    - url: https://github.com/<% organizationName %>/<% repositoryName %>
      title: <% organizationName %>/<% repositoryName %>
      icon: "fa-brands fa-git"
    - url: https://kiratech.awsapps.com/start#/
      title: AWS Console
      icon: "fa-brands fa-aws"
  plugins:
    - name: resources
      value: <%#norm%>{{name}}<%/norm%>-aws-stack
      type: argocd
      icon: fa-solid fa-cookie
      endpointName: argocd
    - name: documentation
      values:
        - "[<% organizationName %>][<% repositoryName %>]README.md"
      type: doc
      icon: fa-solid fa-book
      endpointName: github
    - name: kubernetes
      value: deploymentId
      type: kubernetes
      icon: fa-brands fa-docker
  values:
    organizationName: <% organizationName %>
    repositoryName: <% repositoryName %>
    destinationApiUrl: <% destinationEndpoint.target %>
    description: AWS Stack sample
    endpointName: <% destinationEndpoint.friendlyName %>
    namespace: <% namespace %>
    eks:
      clusterName: <% clusterName %>
    nodeGroup:
      scalingConfig:
        minSize: <% clusterNodes %>
        maxSize: <% maxClusterNodes %>
        desiredSize: <% clusterNodes %>
    network:
      networkName: <% networkName %>
    rds:
      name: <% rdsName %>
      region: <% rdsRegion %>
      allocatedStorage: <% rdsDataDiskSizeGb %>
      dbInstanceClass: <% rdsInstanceClass %>
      engineVersion: "<% rdsEngineVersion %>"
      storageType: <% rdsStorageType %>
    fromRepo:
      schema: https
      organizationName: krateoplatformops
      repositoryName: krateo-template-awsstack
    toRepo:
      schema: https
      organizationName: <% organizationName %>
      repositoryName: <% repositoryName %>
      apiUrl: https://api.github.com
