apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: aws-stack-template
spec:
  owner: mauro.sala@kiratech.it
  title: AWS Stack
  description: Krateo AWS stack Template
  icon: fa-brands fa-aws
  tags:
    - aws
    - eks
    - rds
    - stack
  widgets:
    - title: Name and description
      description: Name and description of the stack.
      properties:
        - title: Name
          description: The name of the component
          required: true
          key: name
        - title: Description
          key: description
          description: Help others understand what this deployment does.
          required: true
          default: AWS Stack sample
        - title: Namespace
          key: namespace
          description: Krateo namespace for the stack.
          required: true
          default: krateo-system
    - title: Kubernetes
      box: Kubernetes cluster name and network name.
      boxStyle: info
      properties:
        - key: clusterName
          title: Cluster Name
          description: The name of the cluster
          required: true
        - key: networkName
          title: Network name
          description: The VPC network to use
          required: true
        - key: clusterNodes
          title: Cluster Nodes
          description: The number of nodes in the cluster
          required: true
          type: number
          default: "3"
        - key: maxClusterNodes
          title: Max Cluster Nodes
          description: The maximum number of nodes in the cluster
          required: true
          type: number
          default: "5"

    - title: Database
      box: Please specify the database name, region, storage type, instance class and engine version.
      boxStyle: warning
      properties:
        - key: rdsName
          title: Rds Name
          description: The name of the RDS
          required: true
        - key: rdsInstanceClass
          title: Rds Instance Class
          description: The instance class of the RDS
          required: true
          default: db.t3.micro
          type: radio
          options:
            - title: db.t3.micro
              value: db.t3.micro
              description: 1 core\n2 vCPU\n1 GB of memory
            - title: db.t3.medium
              value: db.t3.medium
              description: 1 core\n2 vCPU\n2 GB of memory
            - title: db.t3.large
              value: db.t3.large
              description: 2 core\n2 vCPU\n8 GB of memory
        - key: rdsEngine
          title: Rds Engine
          description: The engine of the RDS
          required: true
          default: postgres
        - key: rdsEngineVersion
          title: Rds Engine Version
          description: The engine version of the RDS
          required: true
          default: "13.4"
        - key: rdsDataDiskSizeGb
          title: Rds Disk Size
          description: The size of the RDS disk
          required: true
          default: "10"
          type: number
        - key: rdsRegion
          title: Rds Region
          description: The region of the RDS
          required: true
          default: eu-central-1
        - key: rdsStorageType
          title: Rds Storage Type
          description: The storage type of the RDS
          required: true
          default: standard
          type: radio
          options:
            - title: standard
              value: standard
            - title: gp2
              value: gp2
            - title: io1
              value: io1

    - title: Git repository destination
      box: Set the destination repository.
      properties:
        - title: Endpoint
          key: provider
          required: true
          type: endpoint
        - key: organizationName
          title: Repository Organization
          required: true
          description: Organization name
          default: krateoplatformops
        - key: repositoryName
          title: Repository Name
          required: true
          description: The name of the repository
